### ISSUE TITLE
Adafruit PH6-8S 32x16 panel

### ISSUE THREAD

**Issue by artaslove** [Nurgak/IoT-RGB-LED-Matrix#3]
It sure would be sweet if this program also supported the 32x16 panel!

**Comment by Nurgak** [comment]
The code itself is pretty straight forward to change to support 32x16 or any other size for that matter, see the [configuration defines](https://github.com/Nurgak/IoT-RGB-LED-Matrix/blob/master/config_dummy.h). The only place I optimised too much is [this section](https://github.com/Nurgak/IoT-RGB-LED-Matrix/blob/master/IoTRGBLEDMatrix.ino#L240). Since the display is generated on an Node-RED server mostly it's just a matter of changing what's being sent from there. Basically you can use this for a 32x16 panel without a lot of effort.

**Comment by artaslove** [comment]
Okay, I'll stop being lazy and do it myself :) Thanks for this!
